###
GET http://localhost:3000/coffees?offset=1&limit=1

###
GET http://localhost:3000/coffees/2


###
GET http://localhost:3000/coffees?limit=10&offset=20

###
POST http://localhost:3000/coffees
Content-Type: application/json

{
  "name": "Cappuccino",
  "brand": "3 coracoes",
  "flavors": ["café", "leite", "chocolate"]
}

###
PATCH http://localhost:3000/coffees/2
Content-Type: application/json

{
  "name": "Express"
} 


###
DELETE http://localhost:3000/coffees/1


